Opal.queue(function(Opal) {/* Generated by Opal 1.8.2 */
  var $klass = Opal.klass, $return_val = Opal.return_val, $defs = Opal.defs, $nesting = [], nil = Opal.nil;

  return (function($base, $super) {
    var self = $klass($base, $super, 'Atome');

    
    return $defs(self, '$aui', $return_val("5e85a70cec5b2d68635fc6e9b55bc2a6e2c4d3b8ab3f11c1bd36325628b752c9"))
  })($nesting[0], null)
});
