Opal.queue(function(Opal) {/* Generated by Opal 1.8.2 */
  var $klass = Opal.klass, $return_val = Opal.return_val, $defs = Opal.defs, $nesting = [], nil = Opal.nil;

  return (function($base, $super) {
    var self = $klass($base, $super, 'Atome');

    
    
    $defs(self, '$host', $return_val("web-opal"));
    return $defs(self, '$ip_address', $return_val("192.168.0.13"));
  })($nesting[0], null)
});
